#!/bin/bash

################################################
# Init Script For EC2 with:
#
#   - update yum
#   - installing git
#   - installing JDK 8
#
################################################

################################################
# EXTRA:
# For AMI 2 with amazon-linux-extras enabled,
# it is possible to install corretto8.
#
# See more in 
# https://aws.amazon.com/blogs/compute/running-java-applications-on-amazon-ec2-a1-instances-with-amazon-corretto/
################################################

################################################
# Installing Oracle JDK8: It works in Free Tier
################################################

yum update -y
yum install git -y

################################################
# Code below does not work anymore. It requires
# login for downloading, so you probably gonna
# need to manually download the file and setup
# the JDK by yourself.

## root privileges are required

## Setting up JDK version specific variables
#JAVA_BUILD=8u251-b08
#JAVA_VERSION=8u251
#JDK_BASE_DIR=jdk1.8.0_251

## Downloading
# curl -v -j -k -L -H "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/${JAVA_BUILD}/jdk-${JAVA_VERSION}-linux-x64.tar.gz > jdk-${JAVA_VERSION}-linux-x64.tar.gz

## If you downloaded the file locally, use this extra step to copy it to EC2
# scp -i <your-key-file>.pem jdk-$JAVA_VERSION-linux-x64.tar.gz ec2-user@<public-ip-or-dnsname>:~/.

## Extracting to default location
# cd /opt
# tar xzf jdk-$JAVA_VERSION-linux-x64.tar.gz
# cd $JDK_BASE_DIR/

## Setting up
# alternatives --install /usr/bin/java java /opt/$JDK_BASE_DIR/bin/java 2
# alternatives --config java

# alternatives --install /usr/bin/jar jar /opt/$JDK_BASE_DIR/bin/jar 2
# alternatives --set jar /opt/$JDK_BASE_DIR/bin/jar
# alternatives --set javac /opt/$JDK_BASE_DIR/bin/javac

## Checking Java Version 
# java -version

## Making it globally available
#echo "export JAVA_HOME=/opt/$JDK_BASE_DIR
#export JRE_HOME=/opt/$JDK_BASE_DIR/jre
#export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin" | sudo tee /etc/profile
